version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.11
        commands:
            - pip install --upgrade pip
            - pip install -i https://test.pypi.org/simple/ -r requirements.txt pylint x23176245_django_emails==0.0.1
    pre_build:
        commands:
            - python --version
            - pylint $CODEBUILD_SRC_DIR/*.py
            - pylint $CODEBUILD_SRC_DIR/Take_Care_Django/*.py
artifacts:
    files:
        - '**/*'
